---
title: "LHC-MR"
author: "Shea J. Andrews"
date: "2023-01-18"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '~/gitcode/Snoring-AD-MR')
```

```{r packages}
date = Sys.Date()

library(tidyverse)
library(lhcMR)

# Define column types for summary statistics
coltypes = cols(
  ID = col_character(),
  CHROM = col_double(),
  POS = col_double(),
  REF = col_character(),
  ALT = col_character(),
  AF = col_double(),
  TRAIT = col_character(),
  BETA = col_double(),
  SE = col_double(),
  Z = col_double(),
  P = col_double(),
  N = col_double(),
  OR = col_double(),
  OR_L95 = col_double(),
  OR_U95 = col_double(),
  DIR = col_character(),
  G1000_ID = col_character(),
  G1000_VARIANT = col_character(),
  DBSNP_ID = col_character(),
  DBSNP_VARIANT = col_character(),
  OLD_ID = col_character(),
  OLD_VARIANT = col_character()
)

```

## Step 1: Reading in and merging Data
```{r ld}
## File paths needed for the analysis
LD.filepath = "resources/lhcMR/LDscores_filtered.csv" # LD scores
rho.filepath = "resources/lhcMR/LD_GM2_2prm.csv" # local/SNP-specfic LD scores

ld = "resources/GenomicSEM/eur_w_ld_chr/"
hm3 = "resources/GenomicSEM/w_hm3.snplist"

```

```{r read_exposure}
# Snoring
exposure_path = "resources/Campos2020snor.chrall.CPRA_b37.tsv.gz"
snoring_ss <- read_tsv(exposure_path, comment = "##",  col_types = coltypes, 
                        col_select = c(DBSNP_ID, CHROM, POS, REF, ALT, AF, BETA, SE, Z, P, N))  %>%
  rename(SNP = DBSNP_ID) %>%
  mutate(N = 408317)

# Snoring bmi adjusted 

snorbmi_path = "resources/Campos2020snorbmiadj.chrall.CPRA_b37.tsv.gz"

snorbmiadj_ss <- read_tsv(snorbmi_path, comment = "##",  col_types = coltypes, 
                        col_select = c(DBSNP_ID, CHROM, POS, REF, ALT, AF, BETA, SE, Z, P, N))  %>%
  rename(SNP = DBSNP_ID) %>%
  mutate(N = 407066)


```


```{r read_outcome}
# Clinical AD 
outcome_path = "resources/Kunkle2019load_stage123.chrall.CPRA_b37.tsv.gz"
AD_ss <- read_tsv(outcome_path, comment = "##",  col_types = coltypes, 
                        col_select = c(DBSNP_ID, CHROM, POS, REF, ALT, AF, BETA, SE, Z, P, N))  %>%
  # filter(!(chr.outcome == 19 & between(pos.outcome, 44912079, 45912079)))
  rename(SNP = DBSNP_ID) 

# AD/dementia 
dementia_path = "resources/Bellenguez2022load.chrall.CPRA_b37.tsv.gz"
dementia_ss = read_tsv(
    dementia_path, comment = "##", col_types = coltypes, # n_max = 100,
    col_select = c(DBSNP_ID, CHROM, POS, REF, ALT, AF, BETA, SE, Z, P, N))  %>%
    filter(between(AF, 0.001, 0.999)) %>%
    filter(nchar(REF) == 1 & nchar(ALT) == 1) %>%
    filter(!is.na(DBSNP_ID)) %>%
    rename(SNP = DBSNP_ID) 

```

```{r merge}
## Step 1
### Snoring + AD
snoring_ad.names=c("Snoring","AD")
snoring_ad.files = list(snoring_ss, AD_ss)
snoring_ad_df = merge_sumstats(snoring_ad.files, snoring_ad.names, LD.filepath, rho.filepath)

### Snoring + Dementia
snoring_dem.names=c("Snoring","Dementia")
snoring_dem.files = list(snoring_ss, dementia_ss)
snoring_dem_df = merge_sumstats(snoring_dem.files, snoring_dem.names, LD.filepath, rho.filepath)

### Snoring bmi adjusted
snorbmiadj_ad.names=c("SnoringBMIadj","AD")
snorbmiadj_ad.files = list(snorbmiadj_ss, AD_ss)
snorbmi_ad_df = merge_sumstats(snorbmiadj_ad.files, snorbmiadj_ad.names, LD.filepath, rho.filepath)

```


## Step 2: Calculating smart starting points for the likelihood optimisation

```{r read_merge}
# Snoring + AD
snoring_ad_SP_list = calculate_SP(snoring_ad_df,snoring_ad.names,run_ldsc=TRUE,run_MR=TRUE,hm3=hm3,ld=ld,nStep = 2,
                       SP_single=3,SP_pair=50,SNP_filter=10)

# Snoring + Dementia
snoring_dem_SP_list = calculate_SP(snoring_dem_df,snoring_dem.names,run_ldsc=TRUE,run_MR=TRUE,hm3=hm3,ld=ld,nStep = 2,
                       SP_single=3,SP_pair=50,SNP_filter=10)

# Snoring
snorbmi_ad_SP_list = calculate_SP(snorbmi_ad_df,snorbmiadj_ad.names,run_ldsc=TRUE,run_MR=TRUE,hm3=hm3,ld=ld,nStep = 2,
                       SP_single=3,SP_pair=50,SNP_filter=10)

```


## Step 3: Running the likelihood optimisation to estimate the parameters, followed by a block-jackknife procedure to calculate parameter-SE

```{r read_merge}

## Step 3
snoring_ad_res = lhc_mr(snoring_ad_SP_list, snoring_ad.names, paral_method="lapply", nCores = 2, nBlock=200)
snoring_ad_res %>% as_tibble() %>% write_csv(., glue("results/snoring_ad_lhcmr-{date}.csv"))

## Step 3
snoring_dem_res = lhc_mr(snoring_dem_SP_list, snoring_dem.names, paral_method="lapply", nCores = 2, nBlock=200)
snoring_dem_res %>% as_tibble() %>% write_csv(., glue("results/snoring_dem_lhcmr-{date}.csv"))

## Step 3
snorbmi_ad_res = lhc_mr(snorbmi_ad_SP_list, snorbmiadj_ad.names, paral_method="lapply", nCores = 2, nBlock=200)
snorbmi_ad_res %>% as_tibble() %>% write_csv(., "results/snorbmi_ad_lhcmr-{date}.csv")

```





































